### ISSUE TITLE
平台必须要登录校内VPN

### ISSUE THREAD

**Issue by libra-97** [Li-Chongyi/Lighting-the-Darkness-in-the-Deep-Learning-Era-Open#5]
现在平台好像无法进入了，要登录南开的VPN才可以

**Comment by Li-Chongyi** [comment]
Hi，the bug has been solved.

发自我的iPhone

**Comment by libra-97** [comment]
Thank you so much for your prompt reply, but it seems that I still can't log in. Does it take a while to unravel the restrictions?

**Comment by Li-Chongyi** [comment]
until Monday

发自我的iPhone

**Comment by libra-97** [comment]
That's so great.
